module(name = "cses")

bazel_dep(name = "rules_cc", version = "0.2.18")
bazel_dep(name = "rules_shell", version = "0.6.1")

bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    commit = "078ba7675c05bea2666c92d9a8abe200d8547655",
    remote = "https://github.com/helly25/bazel-compile-commands-extractor.git",
)
